[package]
name = "baton"
version = "0.1.0"
edition = "2021"

[dependencies]
# iceoryx2 = "*"
interprocess = "*"
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"

[lib]
crate-type = ["staticlib"]

[profile.release]
lto = "fat"
