
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Softwares/cmake-3.31.0-rc3-windows-x86_64/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
...
